upload containers

diff --git a/.github/workflows/create_container.yaml b/.github/workflows/create_container.yaml
--- a/.github/workflows/create_container.yaml
+++ b/.github/workflows/create_container.yaml
@@ -74,7 +74,7 @@ jobs:
         run: docker images
 
       - name: Check image exists before push
-        run: docker images | grep afce030 || echo "Image not found"
+        run: docker images || echo "Image not found"
 
       - name: push container
         run: |
